env:
  repo: "https://github.com/Malik20A/demo"
  app_version: "8.0.0"
  app_name: "artemis"

name: Trigger auto deployment for testapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ main ]
  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Clone a repo
        run: |
          git clone ${{ env.repo }}
      - name: Switch Branch
        run: |
          cd demo
          git checkout ${{ env.app_version }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/demo
          registryUrl: hussdemo.azurecr.io
          registryUsername: ${{ secrets.TESTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTAPP_REGISTRY_PASSWORD }}
          containerAppName: testapp
          resourceGroup: test
          imageToBuild: hussdemo.azurecr.io/artemis:${{ github.sha }}
          dockerfilePath: Dockerfile
