env:
  repo: "https://github.com/Malik20A/demo"
  app_version: "5.0.0"
  app_name: "artemis"


name: Trigger auto deployment for test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test-AutoDeployTrigger-132ca7b6-1a5f-4fea-876f-35f490a12ec1.yml'

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Clone a repo
        run: |
          git clone ${{ env.repo }}
          ls -ltr

      # - name: Switch Branch
      #   working-directory: ${{ env.app_name }}
      #   run: |
      #     git checkout ${{ env.app_version }}

      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.TEST_AZURE_CREDENTIALS }}

      # - name: Build and push container image to registry
      #   uses: azure/container-apps-deploy-action@v1
      #   with:
      #     appSourcePath: ${{ github.workspace }}
      #     registryUrl: hussdemo.azurecr.io
      #     registryUsername: ${{ secrets.TEST_REGISTRY_USERNAME }}
      #     registryPassword: ${{ secrets.TEST_REGISTRY_PASSWORD }}
      #     containerAppName: test
      #     resourceGroup: hussdemo
      #     imageToBuild: hussdemo.azurecr.io/test:${{ github.sha }}
      #     dockerfilePath: Dockerfile
