env:
  repo: "https://github.com/Malik20A/demo"
  app_version: "5.0.0"
  app_name: "artemis"

name: Trigger auto deployment for test
# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      - main
    paths:
      - '**'
      - '.github/workflows/testapp-AutoDeployTrigger-ae6edbdd-46b5-4163-93d4-f85bac3955e7.yml'

  # Allow manually trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clone the repository
        run: |
          git clone ${{ env.repo }}
          ls -ltr

      - name: Switch to the specified branch
        run: |
          cd demo
          git checkout ${{ env.app_version }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TESTAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/docker-login@v1
        with:
          login-server: hussdemo.azurecr.io
          username: ${{ secrets.TESTAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.TESTAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        run: |
          docker build -t hussdemo.azurecr.io/testapp:${{ github.sha }} -f Dockerfile .
          docker push hussdemo.azurecr.io/testapp:${{ github.sha }}

      - name: Deploy container app to Azure
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: hussdemo.azurecr.io
          registryUsername: ${{ secrets.TESTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTAPP_REGISTRY_PASSWORD }}
          containerAppName: testapp
          resourceGroup: test
          imageToDeploy: hussdemo.azurecr.io/testapp:${{ github.sha }}
          containerAppConfigFile: containerapp.yaml
